---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-sync-timeout
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: argocd-sync-timeout
  apiGroup: rbac.authorization.k8s.io