---
name: Release

on:
  push:
    tags:
      - "*"

permissions:
  packages: write
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: source/
          push: true
          tags: 'ghcr.io/pcanilho/argocd-sync-timeout:latest,ghcr.io/pcanilho/argocd-sync-timeout:${{ github.ref_name }}'
          github-token: ${{ secrets.GITHUB_TOKEN }}